### ISSUE TITLE
Base.Meta.ParserError WHILE SearchLight.Configuration.load_db_connection() |> SearchLight.Database.connect!

### ISSUE THREAD

**Issue by Rytliock** [GenieFramework/SearchLight.jl#16]
When I exec "SearchLight.Configuration.load_db_connection() |> SearchLight.Database.connect!"
I get this error:

ERROR: Base.Meta.ParseError("invalid escape sequence")
Stacktrace:
 [1] #parse#1(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Int64) at .\meta.jl:129
 [2] #parse at .\none:0 [inlined]
 [3] #parse#4(::Bool, ::Bool, ::Function, ::String) at .\meta.jl:164
 [4] parse(::String) at .\meta.jl:164

Then I made a further attempt：
![image](https://user-images.githubusercontent.com/17492992/55600956-f4792d00-5790-11e9-88d7-fcdf85b6c2a8.png)
It seems like @__DIR__ not work in Meta.parse()

**Comment by LeieXoyo** [comment]
![image](https://user-images.githubusercontent.com/17492992/55601104-b03a5c80-5791-11e9-8738-b63f6f290fba.png)
If 'dir' from hardcode instead of @__DIR__, this is working fine

**Comment by essenciary** [comment]
Might be a Windows issue... I'll run a test, thank you

**Comment by essenciary** [comment]
I've been running on Windows for the last few weeks and haven't encountered the problem anymore, so I assume it's been addressed by other updates. Closing but feel free to reopen if it still comes up.
