### ISSUE TITLE
postgresql datetime should map to timestamp?

### ISSUE THREAD

**Issue by huaxk** [GenieFramework/SearchLight.jl#17]
database_adapters/PostgreSQLDatabaseAdapter.jl line:32
:datetime => :DATETIME  maybe :datetime => :TIMESTAMP?

**Comment by essenciary** [comment]
Yes, I think that's right - needs some testing though :-s

**Comment by UniqueTokens** [comment]
@huaxk Please check and then close.
See [issue #52](https://github.com/GenieFramework/SearchLightPostgreSQL.jl/pull/12)
