### ISSUE TITLE
Integer limit = 4 turn into bigint (4) in postgresql version 10 and 12

### ISSUE THREAD

**Issue by VoyagesDivins** [GenieFramework/SearchLight.jl#52]
**Describe the bug**
Migration  cannot execute on PostgreSQL because "limit = 4" parameter translate into "BIGINT (4)" .

**Error stacktrace**
[error | LibPQ]: SyntaxError: ERROR:  syntax error de syntax near « ( »
LINE 1: ...ATE TABLE movies (id SERIAL  PRIMARY KEY  , year BIGINT (4))

**To reproduce**
execute a migration containing
      column(:year, :integer, limit = 4)

**Expected behavior**
Should create a table with column year of type integer

**Additional context**

`julia> versioninfo()`
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

`pkg> st`
     Project Watchtonight v0.1.0
      Status `D:\devs\tests\Genie\Watchtonight\Project.toml`
  [c43c736e] Genie v4.16.0
  [6d011eab] Inflector v1.0.1
  [e6f89c97] LoggingExtras v0.4.7
  [739be429] MbedTLS v1.0.3
  [340e8cb6] SearchLight v2.2.0
  [4327cdd6] SearchLightPostgreSQL v2.1.0
  [ade2ca70] Dates
  [56ddb016] Logging

**Comment by essenciary** [comment]
@VoyagesDivins thanks for this. 
@michaelfliegner Looks like the last PR caused this: https://github.com/GenieFramework/SearchLightPostgreSQL.jl/pull/10/files 
Looks like we need to revert that - why did you change it to BIGINT?

**Comment by michaelfliegner** [comment]
Integer on 64Bit Architecture is BIGINT in POSTGRES.
Testing integers for containment in int8ranges for instance requires a cast
to BIGINT. I do not want my keys restricted to 32bit.

My change to BIGINT may be the trigger for the problem but imho the cause
would rather be a parser quirk that confuses a limit clause with a type
cast in the context of not being aware of the BIGINT type. But, of course,
the easiest cure is to retract that map to BIGINT.

 I'll create  a PRQ to restore the clause for :integer and ADD a clause

:bigint => BIGINT,

:integer => :INTEGER,


Regards Michael

**Comment by essenciary** [comment]
Sounds like the most flexible approach @michaelfliegner 
If you're submitting the PR, would you be so kind to also take a look at this please? https://github.com/GenieFramework/SearchLightPostgreSQL.jl/issues/11 Looks like the DATETIME mapping needs changing too. Should take 20s. Thank you

**Comment by UniqueTokens** [comment]
Related: https://github.com/GenieFramework/SearchLightPostgreSQL.jl/issues/11#issue-1179909735

**Comment by VoyagesDivins** [comment]
Not specifying a limit does actually work with BIGINT. Maybe the parser should ignore parameter "limit" when it does not make sense for the db engine ?

**Comment by michaelfliegner** [comment]
Ok. I'll comply with that. But, again, imho mapping DATETIME to INTEGER
reeks of old time weak typing. And Date/Time data types in POSTGRES are
date, timestamp, timestamptz and corresponding interval types. However,
pragmatically viewed, my packages use only TIMESTAMPTZ and TSTZRANGE and I
am not concerned by mapping DATETIME to INTEGER. So I'll retract that one
too.

regards Michael

PS: I'll do it NOW

**Comment by michaelfliegner** [comment]
Done

**Comment by michaelfliegner** [comment]
Just for your information:
The error in
      column(:year, :integer, limit = 4)
is that the limit keyword is misplaced, what should it even mean? Max four
digits?
It doesnt work with BIGINT and just the same.not with INTEGER.

The PRQ remains good in my opinion, as s.o. who wants *BIGINT*, for
instance to reference a BIGSERIAL or create a TSTZ8RANGE, *should write
:bigint *in SearchLight.create_table.

regards Michael

Here my reproduction with the corrected TYPEMAPPING:

[ Info: CREATE TABLE testtstzranges (id BIGSERIAL PRIMARY KEY, i TSTZRANGE
, year INTEGER (4))
[error | LibPQ]: SyntaxError: ERROR:  syntax error at or near "("
LINE 1: ...s (id BIGSERIAL PRIMARY KEY, i TSTZRANGE , *year INTEGER (4))*

**Comment by michaelfliegner** [comment]
Please check and then close.

**Comment by VoyagesDivins** [comment]
I did not mention it but I've found that problem when trying to follow the MVC tutorial of Genie Framework using postgresql instead of sqlite.

I think I should have open an issue on Genie repo about documentation.

Solution would be removing "limit = 4" in tutorial or adding a warning about using postgresql.

**Comment by essenciary** [comment]
@VoyagesDivins - thanks, that makes sense. I need to review, maybe we could ignore limit in Postgres, although I'm not sure if that would work for all types.

**Comment by michaelfliegner** [comment]
Hello! I'm just nosy. Where is "create table ... limit ..." legal DDL?
What I know is "select ... limit ...". Example please?!?

Adrian Salceanu ***@***.***> schrieb am Di., 29. März 2022,
11:50:

**Comment by essenciary** [comment]
In this case `limit` is the name of the Julia argument that is used to add a size limit to various types, ex `INTEGER(10)`, `VARCHAR(255)`, `CHAR(4)`, etc

**Comment by michaelfliegner** [comment]
Varchar and char have a size, but Integer? Is that 10 digits? Or the maximal value? 
Neither oracle nor POSTGRES have sth. likewise to my knowledge.

**Comment by michaelfliegner** [comment]
Thank You

Adrian Salceanu ***@***.***> schrieb am Di., 29. März 2022,
19:20:
