### ISSUE TITLE
Support a DateTime timestamp with more than second accuracy

### ISSUE THREAD

**Issue by andyDoucette** [GenieFramework/SearchLight.jl#58]
I believe SearchLight only supports DateTimes with second accuracy.  Millisecond and Microsecond accuracy are also supported by mysql (I'm not sure about the rest).  Many applications require more than second accuracy.

**Comment by essenciary** [comment]
Can you elaborate on what does this require/imply? How do you implement it in MySQL for example?

**Comment by essenciary** [comment]
Closing due to lack of feedback - please reopen if you have input.
