### ISSUE TITLE
How to map model to existing singular table name

### ISSUE THREAD

**Issue by Vladislav-Zolotaryov** [GenieFramework/SearchLight.jl#61]
Hello.

I have an existing db schema I need to integrate with.
But I cannot seem to find how to override table name for a model or at least disable pluralization of the model name.

`The table name is 'world', the model is 'World', but it is always queried as 'worlds'.`

Is this possible? If no, please add such a feature.

**Comment by FrankUrbach** [comment]
The easiest way to get it right is implementing the name of your table by yourself:

'''julia
function SearchLigth.table(m::Type(World))::String
        "world"
end
'''
This should be sufficient. Your World model has to be a subtype of AbstractModel.
That's it.

HTH Frank

**Comment by Vladislav-Zolotaryov** [comment]
Thank you!
